### ISSUE TITLE
Consider Adding an API for Lens support

### ISSUE THREAD

**Issue by wgottschalk** [Originate/nectarine#56]
Watching the ART session today, I have some thoughts about the api. I think it can get quite verbose to access the leaf nodes of some of the store states. Consider adding something like lenses to target the leaf node directly.

https://medium.com/@drboolean/lenses-with-immutable-js-9bda85674780#.del0kecii

the examples are a bit terse, but how I think it could look in nectarine is something along the lines of: 
`store.bazLens.$get()` instead of `store.foo.bar.baz.$get()`

**Comment by charlierudolph** [comment]
Interesting. I'm not really certain I understand what you are suggesting. Lens are a functional way to save some reference. They are defined by the user and named what they want. I wouldn't want to do this automatically for every leaf but could forsee the following type of api where a user can specify a shortcut into the slice.

```js
const testSlice = createSlice({
  schema: _ => {
    foo: {
      bar: {
        baz: _
      }
    }
  },
  shortcuts: {
    bazLens: ['foo', 'bar', 'baz']
  }
})

const store = createStore({test: testSlice})

// The following would be equivalent
store.test.bazLens
store.test.foo.bar.baz
```

I'm not certain that would be useful though and would think you could just use an action for the common logic or change you schema to make the data easier to access.

I'm curious why you think its verbose to access the the leaf nodes. In comparison to redux, getting a value from a store with a similar schema you only have the addition of `$get()` at the end. Redux otherwise would have the same path. Setting is more verbose as you need to dig down into the store instead of dispatching a global action type which triggers a reducer that only operates on a portion of the store. We are trading the verbosity for the elimination of those globals and that whole flow.

**Comment by charlierudolph** [comment]
@wgottschalk going to close this for now. Please reopen if there is more you want to discuss around this
